# Generated by Django 5.1 on 2024-10-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webquiz', '0002_quiz_level_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='level',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(default='default_answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(default='Geral', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(default='Médio', max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
