# Generated by Django 5.1 on 2024-10-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webquiz', '0004_rename_created_at_quiz_ccreated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
