# Generated by Django 5.1 on 2024-10-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webquiz', '0005_remove_question_correct_answer_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
