# Generated by Django 5.1 on 2024-10-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webquiz', '0006_quiz_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('Algoritmos e Lógica', 'Algoritmos e Lógica'), ('Sistemas de Informação', 'Sistemas de Informação'), ('Redes de Computadores', 'Redes de Computadores'), ('Programação', 'Programação'), ('Letramento Computacional', 'Letramento Computacional'), ('Computação Desplugada', 'Computação Desplugada'), ('Arquitetura de Computadores', 'Arquitetura de Computadores'), ('Pensamento Computacional', 'Pensamento Computacional'), ('Inteligência Artificial', 'Inteligência Artificial'), ('Ciência de Dados', 'Ciência de Dados')], default='Letramento Computacional', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('Iniciante', 'Iniciante'), ('Básico', 'Básico'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado'), ('Especialista', 'Especialista'), ('Mestre', 'Mestre'), ('Grandmaster', 'Grandmaster')], default='easy', max_length=50),
        ),
    ]
