# Generated by Django 5.1 on 2024-10-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webquiz', '0007_alter_quiz_category_alter_quiz_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('geral', 'Geral'), ('computational_literacy', 'Letramento Computacional'), ('algorithms', 'Algoritmos'), ('data_structures', 'Estruturas de Dados'), ('cybersecurity', 'Cibersegurança')], default='geral', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil'), ('avancado', 'Avançado'), ('expert', 'Especialista'), ('master', 'Mestre'), ('legend', 'Lendário')], default='facil', max_length=50),
        ),
    ]
