# Generated by Django 5.1 on 2024-10-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webquiz', '0008_alter_quiz_category_alter_quiz_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('geral', 'Geral'), ('computational_literacy', 'Letramento Computacional'), ('digital_culture', 'Cultura Digital'), ('computational_thinking', 'Pensamento Computacional'), ('enade', 'ENADE'), ('algorithms', 'Algoritmos'), ('data_structures', 'Estruturas de Dados'), ('cybersecurity', 'Cibersegurança')], default='geral', max_length=100),
        ),
    ]
